[tool.poetry]
name = "drupaljsonapiclient"
version = "1.0.9"
description = "Drupal CMS JSON:API client for Python."
authors = ["Martins Bruvelis <martins.bruvelis@gmail.com>"]
readme = "README.md"
packages = [{include = "drupaljsonapiclient"}]
repository = "https://gitlab.com/martins-bruvelis/drupaljsonapiclient"
documentation = "https://gitlab.com/martins-bruvelis/drupaljsonapiclient/-/blob/main/README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.31.0"
jsonschema = "^4.17.3"
aiohttp = {version = "^3.8.4", optional = true}
aiofiles = {version = "^23.1.0", optional = true}


[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.0.2"
ipywidgets = "^8.0.6"
plotly = "^5.15.0"
jupyter-dash = "^0.4.2"
jupyterlab-hdf = "^1.3.0"
nest-asyncio = "^1.5.6"
tqdm = "^4.65.0"
solara = "^1.16.2"
matplotlib = "^3.7.1"
tabulate = "^0.9.0"
flatjsondict = "^1.0.3"
pandas = "^2.0.2"
pyjanitor = "^0.24.0"
gspread = "^5.9.0"
gspread-pandas = "^3.2.2"
jsonmerge = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
