[build-system]
requires = ["hatchling>=1.8.0", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[project]
name = "tier-sdk"
dynamic = ["version"]
readme = "README.md"
license = "MIT"
description = "TIER Python SDK"
authors = [
    { name = "Owen Voke", email = "development@voke.dev" }
]
keywords = ["tier", "sdk"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
]
requires-python = ">=3.11.0"
dependencies = [
    "requests>=2.28.1"
]

[project.urls]
"Source Code" = "https://github.com/owenvoke/tier-python-sdk"
"Issues" = "https://github.com/owenvoke/tier-python-sdk/issues"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.targets.sdist]
exclude = [
    "/.github",
    "/docs",
    "/tests",
]

[tool.hatch.build.targets.wheel]
packages = ["tier"]

[tool.hatch.envs.default]
dependencies = [
    "black",
    "mypy",
    "pytest==7.1",
    "requests-mock==1.10",
    "types-requests",
]

[tool.hatch.envs.default.scripts]
test = [
    "black --check --diff .",
    "mypy tier",
    "pytest",
]
lint = [
    "black ."
]

[tool.black]
target-version = ["py39", "py310"]
