[tool.poetry]
name = "metaphor-models"
version = "0.19.0"
description = ""
authors = ["Metaphor <dev@metaphor.io>"]
packages = [
    { include = "metaphor" },
]
include = [
  "metaphor/models/__init__.py",
  "metaphor/models/crawler_run_metadata.py",
  "metaphor/models/crawler_run_metadata.json",
  "metaphor/models/metadata_change_event.py",
  "metaphor/models/metadata_change_event.json",
]

[tool.poetry.dependencies]
python = "~=3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
