[project]
name = "sniimapp"
version = "0.0.32"
authors = [
  { name="Rodolfo Lopez", email="1803672F@umich.mx" },
]
description = "Libreria para extraccion de precios SNIIM"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage"    = "https://github.com/rodolfolopezfcca/sniimapp_2"
"Bug Tracker" = "https://github.com/rodolfolopezfcca/sniimapp_2"
