[tool.poetry]
name = "AlekSIS-App-Buelleten"
version = "2.0.dev1"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"
include = [
    { path = "aleksis/**/*.mo", format = ["sdist", "wheel"] },
    { path = "*.rst", format = "sdist" },
    { path = "tox.ini", format = "sdist" }
]

description = "AlekSIS (School Information System) — App Bülleten (Digital Signage)"
authors = ["Tom Teichler <tom.teichler@teckids.org>"]
license = "EUPL-1.2-or-later"
homepage = "https://aleksis.org"
repository = "https://edugit.org/AlekSIS/onboarding//AlekSIS-App-Buelleten"
documentation = "https://aleksis.edugit.io/official/AlekSIS-Core/docs/html/"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[[tool.poetry.source]]
name = "gitlab"
url = "https://edugit.org/api/v4/projects/461/packages/pypi/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
aleksis-core = {version = ">=3.0, <3.2", allow-prereleases = true }

[tool.poetry.dev-dependencies]
aleksis-builddeps = {version=">=2023.1.dev0", allow-prereleases=true}

[tool.poetry.plugins."aleksis.app"]
buelleten = "aleksis.apps.buelleten.apps:DefaultConfig"

[tool.black]
line-length = 100
exclude = "/migrations/"

[tool.curlylint]
include = '\.html'

[tool.curlylint.rules]
aria_role = true
django_forms_rendering = true
image_alt = true
indent = 2
meta_viewport = true
no_autofocus = true
tabindex_no_positive = true

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
