[tool.poetry]
name = "arcan"
version = "1.3.7"
description = "A multiheaded modern data bridging package based on pipeline manifests to integrate between any modern (and old) data stack tools"
authors = ["Carlos D. Escobar-Valbuena <carlosdavidescobar@gmail.com>"]
license = "arcan.ai Non-Commercial Open Source License"
readme = "README.md"
packages = [
    {include = "arcan"},
    {include = "main.py"}
]


[tool.poetry.dependencies]
python = "^3.10"
fastapi = ">=0.98,<0.100"
uvicorn = "^0.22.0"
modal-client = ">=0.49.2509,<0.51.0"
black = "^23.3.0"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
ipykernel = "^6.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
arcan = 'arcan:entrypoint'