[tool.poetry]
name = "cachefunc"
version = "0.2.5"
description = "Caching functions and coroutines result with decorators"
authors = ["Petrov Mikhail <petrov.ma@icloud.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/ma-petrov/cachefunc"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
