[tool.poetry]
name = "botsy"
version = "0.1.34"
description = "An interactive chat program"
authors = ["John Furr <john.furr@gmail.com>"]
readme = "README.md"
include = ["**/*", "sounds/*", "../actions/*"]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
openai = "^0.27.4"
pygments = "^2.15.0"
speechrecognition = "^3.10.0"
pygame = "^2.3.0"
pydub = "^0.25.1"
boto3 = "^1.26.142"
googlesearch-python = "^1.2.3"
newspaper3k = "^0.2.8"
google-api-python-client = "^2.87.0"
click = "^8.1.3"
pytesseract = "^0.3.10"
selenium = "^4.9.1"
pillow = "^9.5.0"
pymongo = "4.3.3"
python-dotenv = "^1.0.0"
scikit-learn = "1.2.2"
joblib = "^1.2.0"
jprint = "^1.6"
tinydb = "^4.8.0"
pyaudio = "^0.2.13"
colorama = "^0.4.6"
botocore = "1.29.165"

[tool.poetry.dev-dependencies]
pytest = "^7.3.1"

[tool.poetry.scripts]
botsy = "run_botsy:cli"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"


[tool.poetry.group.converse.dependencies]
openai = "^0.27.8"
python-dotenv = "^1.0.0"
boto3 = "^1.26.165"
pydub = "^0.25.1"
pygame = "^2.5.0"
speechrecognition = "^3.10.0"
jprint = "^1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "botsy"
authors = [
  { name="John Furr", email="john.furr@gmail.com" },
]
description = "An interactive chat program"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/gnulnx/botsy"

