[tool.poetry]
name = "bi_etl"
version = "1.4.3"
description = "Python ETL Framework"
keywords=["etl"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 5 - Production/Stable",
    "Topic :: Database",
]
authors = ["Derek Wood <bietl_info@bietl.dev>"]
#homepage = "https://bietl.dev/"
documentation = "https://bietl.dev/docs/"
readme="README.md"
license = "MIT"
repository = "https://github.com/arcann/bi_etl"

[tool.poetry.dependencies]
python = "^3.7,<4.0"
config-wrangler = ">= 0.5.5"
SQLAlchemy = ">=1.4.35"
semidbm = ">=0.5.1"
psutil = ">=5.7.2"
openpyxl = ">=3.0.5"
btrees = ">=4.7.2"
gevent = ">=21.8.0"
sqlparse = ">=0.4.2"
keyring = ">=21.1.0"
pydicti = ">=1.1.6"
more-itertools = ">=9.0.0"

# Optional
fastavro = {version = ">=1.0.0", optional = true}
pyarrow = {version = ">=10.0.1", optional = true}
boto3 = {version = ">=1.21", optional = true}
psycopg2 = {version = ">=2.8.6", optional = true}
jira = {version = ">=3.1.1", optional = true}
slack-sdk = {version = ">=3.19.5", optional = true}
pykeepass = {version = ">=4.0.5", optional = true}

[tool.poetry.extras]
# Install with:
# poetry install -E keyring
keyring = ["keyring"]

pykeepass = ["pykeepass"]

jira = ["jira"]

slack = ["slack-sdk"]

# poetry install -E test
test = ["psycopg2", "testcontainers"]

[tool.poetry.dev-dependencies]
toml = "^0.10.1"
testcontainers = {version = ">=3.5.4", extras = ["mysql oracle postgresql mssqlserver"]}
tox = "^3.25.0"
Jinja2 = ">=3.1.2"
boto3 = ">=1.26"
fastavro = ">=1.5.3"
Sphinx = ">=4.5,<5.0"
sphinx-paramlinks = ">=0.5.4"
sphinx-pydantic = ">=0.1.1"
autodoc-pydantic = ">=1.7.2"
# sphinx-autodoc-annotation = "^1.0-1"
psycopg2 = ">=2.9.3"
sphinx-sizzle-theme = ">=0.1.1"
sphinx-autobuild = "^2021.3.14"
oracledb = ">=1.2.0"
pip = ">=22.1.2"
slack-sdk = ">=3.19.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
