[project]
name = "datascience_cookiecutter"
version = "0.2.1"
description = ""
authors = [
    { name = "", email = "" },
]
dependencies = [
    "pydantic>=2.0",
    "loguru>=0.7.0",
    "click>=8.1.3",
]
requires-python = ">=3.7"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Environment :: Console",
    "Typing :: Typed",
]

[project.license]
text = "MIT"

[project.optional-dependencies]
lint = [
    "pytest>=7.4.0",
    "ruff>=0.0.275",
    "black>=23.3.0",
    "isort>=5.11.5",
    "mypy>=1.4.1",
]

[project.scripts]
cookiecutter = "datascience_cookiecutter.__main__:create_project"

[tool.pdm.urls]
GitHub = "https://github.com/raoulg/datascience-cookiecutter"

[tool.mypy]
ignore_missing_imports = true
strict_optional = true
warn_unreachable = true
pretty = true
show_error_codes = true

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"
