[tool.poetry]
name = "AlekSIS-App-Postbuero"
version = "2.0.1.dev0"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"

description = "AlekSIS (School Information System) — App Postbuero (Mail server management)"
authors = ["Tom Teichler <tom.teichler@teckids.org>"]
license = "EUPL-1.2"
homepage = "https://aleksis.org"
repository = "https://edugit.org/AlekSIS/Onboarding/AlekSIS-App-Postbuero/AlekSIS-App-Postbuero"
documentation = "https://aleksis.edugit.io/official/AlekSIS/docs/html/"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[[tool.poetry.source]]
name = "gitlab"
url = "https://edugit.org/api/v4/projects/461/packages/pypi/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
AlekSIS-Core = "^3.0b0"

[tool.poetry.dev-dependencies]
aleksis-builddeps = "*"

[tool.poetry.plugins."aleksis.app"]
postbuero = "aleksis.apps.postbuero.apps:PostBueroConfig"

[tool.black]
line-length = 100
exclude = "/migrations/"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
