[tool.poetry]
authors = ["Daniel CAUNE <daniel@bootloader.studio>"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries",
]
description = "Command-line Interface (CLI) responsible for returning the list of the assets of an Unreal Engine project into a JSON structure"
include = [
    "CHANGELOG.md",
]
keywords = ["cli", "tool", "utility", "unreal", "engine", "asset", "inventory", "dump", "json"]
license = "SEE LICENSE IN <LICENSE.md>"
name = "uasset-dump"
packages = [{ include = "bootloader" }]
readme = "README.md"
repository = "https://github.com/bootloader-studio/cli-uasset-dump"
version = "0.0.12"

[tool.poetry.dependencies]
perseus-core-library = "^1.19.3"
python = "^3.9"

[tool.poetry.scripts]
ueprjver = 'bootloader.ue.cli.uassetdump:run'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
