[tool.poetry]
name = "testdwg"
version = "0.2.0"
description = ""
authors = ["yatmanov <yatmanov@megaputer.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
