[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hubrdvmairie"
version = "2.22.0"
description = "API de la plateforme de recherche de rendez-vous mairies"
readme = "README.md"
authors = [{ name = "ANTS", email = "ants-rdvmairie@interieur.gouv.fr" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["rendez-vous", "mairie", "proxy", "prÃ©-demande", "passeport", "CNI"]
dependencies = [
    "asyncio == 3.4.3",
    "fastapi == 0.87.0",
    "fastapi-utils == 0.2.1",
    "geopy == 2.2.0",
    "pydantic == 1.9.1",
    "python-dotenv == 0.20.0",
    "slowapi == 0.1.6", 
    "uvicorn == 0.18.2",
    "websockets == 10.3",
    "pytest-mock == 3.8.2",
    "secweb == 1.6.0",
    "markdown == 3.4.1",
    "unidecode == 1.3.6",
    "httpx == 0.23.3",
    "requests == 2.28.1",
    "msoffcrypto-tool == 5.0.1",
    "openpyxl == 3.1.1"
]
requires-python = ">=3.10"

[project.optional-dependencies]
dev = ["black", "flake8", "isort", "autoflake", "bandit", "pytest", "pytest-asyncio", "pytest-mock", "pytest-cov", "coverage"]

[project.urls]
documentation = "https://rendez-vous-api.france-identite.fr/docs"
repository = "https://gitlab.com/france-identite/rendez-vous-mairie"