[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "outlierapp"
version = "0.1"
authors = [
  { name="Volvo", email="chatterjeedevosmita267@gmail.com" },
]
description = "Anomaly Detection package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/devosmitachatterjee2018/AnomalyDetectionApp"
"Bug Tracker" = "https://github.com/devosmitachatterjee2018/AnomalyDetectionApp/issues"