[tool.pytest.ini_options]
pythonpath = [
  ".",
]
addopts = [
    "--import-mode=importlib",
]

[tool.poetry]
name = "video_process"
version = "0.2.5"
description = "A package for video processing"
authors = ["shao wei <shaowei_8910@163.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pyass = "0.1.1"
ffmpeg-python = "0.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
